---
#NOTE: Ubuntu/Debian-specific !!
- name: add prereqs
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ docker_prereqs }}"
    state: present
  tags:
    - docker

- name: add docker key
  # deprecated (but use for now), as other distros added, change to variable form
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: capture distro name
  ansible.builtin.command:
    argv:
      - lsb_release
      - -cs
  register: distro_name
  # might be available from facts; verify this
  tags:
    - docker

- name: add docker repo
  ansible.builtin.apt_repository:
    # this too should be "variablized" ;)
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ distro_name.stdout }} stable"
    state: present
  tags:
    - docker

- name: update cache and install docker
  ansible.builtin.apt:
    update_cache: yes
    name: "{{ docker_pkgs }}"
    state: present
  tags:
    - docker
...
